### ISSUE TITLE
TImeline not working 

### ISSUE THREAD

**Issue by pgarciabdfir** [DFIRKuiper/Kuiper#20]
Hi,

Kuiper is working fine for us except for the timeline. It always is empty, no matter how many events have been selected in the Artifacts tab.

Where could we see what can be happening?

Congratulations for Kuiper. It looks a great DFIR tool. 

Best regards

**Comment by salehmuhaysin** [comment]
what version you are using ?

**Comment by pgarciabdfir** [comment]
Hi, Saleh.

It's 2.0.0

Best regards,
     Pedro

**Comment by salehmuhaysin** [comment]
i faced the issue of not showing the timeline tags before and i remember is solved it in version 2.0.9 (v2.0.9 was in the repo but did not create a release for it, i just created the release now)

during the mean time, you can use the browse artifacts page  to show the tagged records using the search 
```tag_id:*```

**Comment by pgarciabdfir** [comment]
Thank you very mucho for your answer. I will download the new version as soon as be available.

Best regards, 
              Pedro

**Comment by pgarciabdfir** [comment]
Hi,

I have reinstalled Kuiper in a brand new machine, and feed it with new evidences for a new case, but unfortunately this issue still remains

Besides,  the version showed by kuiper is 2.0.0.

Best regards.

**Comment by salehmuhaysin** [comment]
hi,

could you check the console window for the browser (developer tools -> Console)

**Comment by salehmuhaysin** [comment]
please check the latest release, it should be fixed
if you still face the same issue, please open issue again

**Comment by pgarciabdfir** [comment]
OK. I will check it. Sorry for not answering, I were busy
